{
  "formatVersion": "1.1",
  "component": {
    "group": "com.digid",
    "module": "digid-sdk",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "digid-sdk-1.1.0.aar",
          "url": "digid-sdk-1.1.0.aar",
          "size": 231802,
          "sha512": "b3ffbaab6f81bffcfea1a86e1bf24a410bddb5a055df12ef2790b13fcb8a9e2ba2dde5ea90937fdb4e9ba1ec379f446d78eba7dfbefccf1b80f0528af629dec6",
          "sha256": "732ef7f3550d54bc120754529e9955562ed7e44dfa8b09cd00065e8259adb371",
          "sha1": "6de90b37916370415eeffc68d7a4e7cfdbdf7be5",
          "md5": "b881bbf7990acf5211bba94e80c4de8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "me.didit",
          "module": "didit-sdk",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "digid-sdk-1.1.0.aar",
          "url": "digid-sdk-1.1.0.aar",
          "size": 231802,
          "sha512": "b3ffbaab6f81bffcfea1a86e1bf24a410bddb5a055df12ef2790b13fcb8a9e2ba2dde5ea90937fdb4e9ba1ec379f446d78eba7dfbefccf1b80f0528af629dec6",
          "sha256": "732ef7f3550d54bc120754529e9955562ed7e44dfa8b09cd00065e8259adb371",
          "sha1": "6de90b37916370415eeffc68d7a4e7cfdbdf7be5",
          "md5": "b881bbf7990acf5211bba94e80c4de8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "digid-sdk-1.1.0-sources.jar",
          "url": "digid-sdk-1.1.0-sources.jar",
          "size": 59192,
          "sha512": "ededeb4702655c27cbfe222e41444aca6b9f65cc92b3873f6bb62cd45c98dc7e9faa99a60bd426a7a566f396189c4273433f43ebfaff0b856c74b2deb9071675",
          "sha256": "5efafdb7ac5e24d477bbeecd8a8615dac07ee957b0872057938cafe4d965e127",
          "sha1": "eaa46ab258aaf907f6247f8a4e9c01cbb78e04e9",
          "md5": "7338d7112369397e6450446a72d23d7c"
        }
      ]
    }
  ]
}
