{
  "formatVersion": "1.1",
  "component": {
    "group": "me.didit",
    "module": "didit-sdk-autodetection",
    "version": "4.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.didit",
          "module": "didit-sdk-core",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "didit-sdk-autodetection-4.5.3.aar",
          "url": "didit-sdk-autodetection-4.5.3.aar",
          "size": 13857,
          "sha512": "a4d6697b6579315bf99b72be7f4614fbadb3359e5bbd33ff2fad1c82b620336430030346e120ba2052c949ba9ccb2bbdb0118ead0012237ce2e4d32f00b746c9",
          "sha256": "5d2d1c8766eed5de35278d90e1ce96d2bf46a0f32ba9dfc700b1f098fb3d800c",
          "sha1": "16485ce595e394e3c203f2403c38d38ddd0e4c3b",
          "md5": "3d67eefec3ce34aa740a241f298d4c8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.google.mediapipe",
          "module": "tasks-vision",
          "version": {
            "requires": "0.10.29"
          }
        },
        {
          "group": "me.didit",
          "module": "didit-sdk-core",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "didit-sdk-autodetection-4.5.3.aar",
          "url": "didit-sdk-autodetection-4.5.3.aar",
          "size": 13857,
          "sha512": "a4d6697b6579315bf99b72be7f4614fbadb3359e5bbd33ff2fad1c82b620336430030346e120ba2052c949ba9ccb2bbdb0118ead0012237ce2e4d32f00b746c9",
          "sha256": "5d2d1c8766eed5de35278d90e1ce96d2bf46a0f32ba9dfc700b1f098fb3d800c",
          "sha1": "16485ce595e394e3c203f2403c38d38ddd0e4c3b",
          "md5": "3d67eefec3ce34aa740a241f298d4c8c"
        }
      ]
    }
  ]
}
