{
  "formatVersion": "1.1",
  "component": {
    "group": "com.digid",
    "module": "digid-sdk",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "digid-sdk-2.0.1.aar",
          "url": "digid-sdk-2.0.1.aar",
          "size": 267040,
          "sha512": "392b57644c052cca6a917827bb982ce576ae5a0cbcfec00d36cef191b99d4ccb2ec2f8d821442be772b5729b789be172219ea0e26be76834342f1b2a539ddca6",
          "sha256": "b836ad156455e5acc8e9fecb52e59e2bfb80122acff24d22bc7309b5bbdc2a59",
          "sha1": "b26920353569ddc94beb017eb33cce39d20f11b8",
          "md5": "0c1d8d13b58ee23866d04ba7c3757301"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "me.didit",
          "module": "didit-sdk",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "digid-sdk-2.0.1.aar",
          "url": "digid-sdk-2.0.1.aar",
          "size": 267040,
          "sha512": "392b57644c052cca6a917827bb982ce576ae5a0cbcfec00d36cef191b99d4ccb2ec2f8d821442be772b5729b789be172219ea0e26be76834342f1b2a539ddca6",
          "sha256": "b836ad156455e5acc8e9fecb52e59e2bfb80122acff24d22bc7309b5bbdc2a59",
          "sha1": "b26920353569ddc94beb017eb33cce39d20f11b8",
          "md5": "0c1d8d13b58ee23866d04ba7c3757301"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "digid-sdk-2.0.1-sources.jar",
          "url": "digid-sdk-2.0.1-sources.jar",
          "size": 67090,
          "sha512": "ad366cc313c459fc595daaa77172b52ecd44cb8672f1b7113ca7d640d2abaaf3c3f409877119458adc2daef74d0adbc8aadcd86a3bb90af3ce55fa9db80a3a3f",
          "sha256": "b691801a0956ba4f8e00ddd6877c37437fe338267f0f383076566b95225ebe5d",
          "sha1": "89dd8e4b4994f9b33f5dd2aed0847335c70c8947",
          "md5": "e9f12b8f87703b78ec63734aa21223bc"
        }
      ]
    }
  ]
}
