{
  "formatVersion": "1.1",
  "component": {
    "group": "com.digid",
    "module": "digid-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "digid-sdk-1.0.0.aar",
          "url": "digid-sdk-1.0.0.aar",
          "size": 197958,
          "sha512": "6c1dce8b71e38c5b831c71b8d376b2db6be8637be1044b5c4a7b9cfc264dcda4923ff77850194435abea7f7e3e24e71e5b5a80c35e4fffce3391596f04fef08b",
          "sha256": "c4f2f5c4b5911401d1e6c1df5716cf329f97db9006540fb8d20b88715a28d37e",
          "sha1": "c9f3a111a1ffaa070299dcea9714030a393d85b8",
          "md5": "58e07b2c4610bad5f160b09f2eebbe0e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "me.didit",
          "module": "didit-sdk",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "digid-sdk-1.0.0.aar",
          "url": "digid-sdk-1.0.0.aar",
          "size": 197958,
          "sha512": "6c1dce8b71e38c5b831c71b8d376b2db6be8637be1044b5c4a7b9cfc264dcda4923ff77850194435abea7f7e3e24e71e5b5a80c35e4fffce3391596f04fef08b",
          "sha256": "c4f2f5c4b5911401d1e6c1df5716cf329f97db9006540fb8d20b88715a28d37e",
          "sha1": "c9f3a111a1ffaa070299dcea9714030a393d85b8",
          "md5": "58e07b2c4610bad5f160b09f2eebbe0e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "digid-sdk-1.0.0-sources.jar",
          "url": "digid-sdk-1.0.0-sources.jar",
          "size": 47123,
          "sha512": "5fdf87567c79abfe8c2a756ae8cbcba8bb7689dbf1a88fb5706ed720a56b61028d6625f07a2b34f92cc2ea224cc4285940570be5fd1f4bfeec96d52e651a90ff",
          "sha256": "103a1e224f7803851eb8e91705821ed4026139e2fd20ee2b1977a15c25429c2e",
          "sha1": "6188abfb93583ae8123b2b6ad64cb11f0de1fa46",
          "md5": "44b55bcddb5fe7cfcac7f7baa7dfee34"
        }
      ]
    }
  ]
}
