{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.0.2"
    }
  },
  "component" : {
    "group" : "com.github.komputing",
    "module" : "khash",
    "version" : "1.1.1",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "metadataApiElements",
    "attributes" : {
      "org.gradle.usage" : "kotlin-metadata",
      "org.jetbrains.kotlin.platform.type" : "common"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-common",
      "version" : {
        "requires" : "1.5.10"
      }
    } ],
    "files" : [ {
      "name" : "ripemd160-1.1.1.jar",
      "url" : "ripemd160-1.1.1.jar",
      "size" : 4890,
      "sha512" : "41adc6784df25fc267b0835702e4b172d6512b92f3b5433304991754247c7a7d57f64342e8594773c04f7575bcc47a9567f52975f477ea84d4067db8d1285c9e",
      "sha256" : "3fb92417c8316876062db234a74205f5d781752c54128790d38a093e00e6411c",
      "sha1" : "ffffe39757b85103303e0220d9639a06f71df815",
      "md5" : "8afdc7fcbe80a5ae2a5fed0fd6de30bd"
    } ]
  }, {
    "name" : "commonMainMetadataElements",
    "attributes" : {
      "org.gradle.usage" : "kotlin-api",
      "org.jetbrains.kotlin.platform.type" : "common"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-common",
      "version" : {
        "requires" : "1.5.10"
      }
    } ],
    "files" : [ {
      "name" : "ripemd160-1.1.1.jar",
      "url" : "ripemd160-1.1.1.jar",
      "size" : 2221,
      "sha512" : "197c1a4e3e7a028e4ce4c9ca13923c99a383e3184e09cfba6588ad5cd1fd843b780db504a2329edd237f8361a9f1d08d92ca1dd3f1172230253fe210debc69c6",
      "sha256" : "35323636ad93f8169b35a1a2799108aadce2a01127ccf91a7594ad9dd77b9ed5",
      "sha1" : "d89eb6f40daf66a508bae3fd40e3975d9377e64c",
      "md5" : "9209f97582a23cf1fb30eda1aaee354f"
    } ]
  }, {
    "name" : "jsLegacyApiElements-published",
    "attributes" : {
      "org.gradle.usage" : "kotlin-api",
      "org.jetbrains.kotlin.js.compiler" : "legacy",
      "org.jetbrains.kotlin.platform.type" : "js"
    },
    "available-at" : {
      "url" : "../../ripemd160-js/1.1.1/ripemd160-js-1.1.1.module",
      "group" : "com.github.komputing.khash",
      "module" : "ripemd160-js",
      "version" : "1.1.1"
    }
  }, {
    "name" : "jsLegacyRuntimeElements-published",
    "attributes" : {
      "org.gradle.usage" : "kotlin-runtime",
      "org.jetbrains.kotlin.js.compiler" : "legacy",
      "org.jetbrains.kotlin.platform.type" : "js"
    },
    "available-at" : {
      "url" : "../../ripemd160-js/1.1.1/ripemd160-js-1.1.1.module",
      "group" : "com.github.komputing.khash",
      "module" : "ripemd160-js",
      "version" : "1.1.1"
    }
  }, {
    "name" : "jsIrApiElements-published",
    "attributes" : {
      "org.gradle.usage" : "kotlin-api",
      "org.jetbrains.kotlin.js.compiler" : "ir",
      "org.jetbrains.kotlin.platform.type" : "js"
    },
    "available-at" : {
      "url" : "../../ripemd160-js/1.1.1/ripemd160-js-1.1.1.module",
      "group" : "com.github.komputing.khash",
      "module" : "ripemd160-js",
      "version" : "1.1.1"
    }
  }, {
    "name" : "jsIrRuntimeElements-published",
    "attributes" : {
      "org.gradle.usage" : "kotlin-runtime",
      "org.jetbrains.kotlin.js.compiler" : "ir",
      "org.jetbrains.kotlin.platform.type" : "js"
    },
    "available-at" : {
      "url" : "../../ripemd160-js/1.1.1/ripemd160-js-1.1.1.module",
      "group" : "com.github.komputing.khash",
      "module" : "ripemd160-js",
      "version" : "1.1.1"
    }
  }, {
    "name" : "jvmApiElements-published",
    "attributes" : {
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "available-at" : {
      "url" : "../../ripemd160-jvm/1.1.1/ripemd160-jvm-1.1.1.module",
      "group" : "com.github.komputing.khash",
      "module" : "ripemd160-jvm",
      "version" : "1.1.1"
    }
  }, {
    "name" : "jvmRuntimeElements-published",
    "attributes" : {
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "available-at" : {
      "url" : "../../ripemd160-jvm/1.1.1/ripemd160-jvm-1.1.1.module",
      "group" : "com.github.komputing.khash",
      "module" : "ripemd160-jvm",
      "version" : "1.1.1"
    }
  } ]
}