{
  "formatVersion": "1.1",
  "component": {
    "group": "me.didit",
    "module": "didit-sdk-autodetection",
    "version": "4.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.didit",
          "module": "didit-sdk-core",
          "version": {
            "requires": "4.7.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "didit-sdk-autodetection-4.7.4.aar",
          "url": "didit-sdk-autodetection-4.7.4.aar",
          "size": 16577,
          "sha512": "6a99c277202d54d367acaa5502603f9e2c42ef7a99de5ddd70dc9698d84644becae9c7dedf594a3e52592be4a0099c72f89c99a044b966b4146ebf1a4cc59468",
          "sha256": "2ecadf224a749741313dd84e24acbb89542f194e1b32f7bbf95423a067ecb1da",
          "sha1": "fb7d789bcf03def96ee5d1c539946932b1f7b48a",
          "md5": "89240db90955a59c30286b0a90936bdc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.google.mediapipe",
          "module": "tasks-vision",
          "version": {
            "requires": "0.10.29"
          }
        },
        {
          "group": "me.didit",
          "module": "didit-sdk-core",
          "version": {
            "requires": "4.7.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "didit-sdk-autodetection-4.7.4.aar",
          "url": "didit-sdk-autodetection-4.7.4.aar",
          "size": 16577,
          "sha512": "6a99c277202d54d367acaa5502603f9e2c42ef7a99de5ddd70dc9698d84644becae9c7dedf594a3e52592be4a0099c72f89c99a044b966b4146ebf1a4cc59468",
          "sha256": "2ecadf224a749741313dd84e24acbb89542f194e1b32f7bbf95423a067ecb1da",
          "sha1": "fb7d789bcf03def96ee5d1c539946932b1f7b48a",
          "md5": "89240db90955a59c30286b0a90936bdc"
        }
      ]
    }
  ]
}
