{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.3.3"
    }
  },
  "component" : {
    "group" : "com.github.komputing",
    "module" : "kethereum",
    "version" : "0.86.0",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "8",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "files" : [ {
      "name" : "bip39-0.86.0.jar",
      "url" : "bip39-0.86.0.jar",
      "size" : 9769,
      "sha512" : "e7cf3ed82917588fedd6e43ff1caf08da8ebad49085e9661189a4672894f61c99be95629b948d50c6f12cdebc31e3f9a6d5f23ecc905cd2208849d46be4f6e89",
      "sha256" : "37484bac4da37fa1802cc6868f72d5e629f41a03d9697aa18d0abe3c6ae47936",
      "sha1" : "6ec1c9bec76e168dc9028137a00ace68687b11ca",
      "md5" : "5d39cc91860ee84e3404e0d5c812e4fb"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "8",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "dependencies" : [ {
      "group" : "com.github.komputing.kethereum",
      "module" : "bip32",
      "version" : {
        "requires" : "0.86.0"
      }
    }, {
      "group" : "com.github.komputing.kethereum",
      "module" : "extensions_kotlin",
      "version" : {
        "requires" : "0.86.0"
      }
    }, {
      "group" : "com.github.komputing.kethereum",
      "module" : "crypto",
      "version" : {
        "requires" : "0.86.0"
      }
    }, {
      "group" : "com.github.komputing.kethereum",
      "module" : "crypto_api",
      "version" : {
        "requires" : "0.86.0"
      }
    }, {
      "group" : "com.github.komputing",
      "module" : "khex",
      "version" : {
        "requires" : "1.1.2"
      }
    }, {
      "group" : "com.github.komputing.khash",
      "module" : "sha256",
      "version" : {
        "requires" : "1.1.1"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "1.6.10"
      }
    } ],
    "files" : [ {
      "name" : "bip39-0.86.0.jar",
      "url" : "bip39-0.86.0.jar",
      "size" : 9769,
      "sha512" : "e7cf3ed82917588fedd6e43ff1caf08da8ebad49085e9661189a4672894f61c99be95629b948d50c6f12cdebc31e3f9a6d5f23ecc905cd2208849d46be4f6e89",
      "sha256" : "37484bac4da37fa1802cc6868f72d5e629f41a03d9697aa18d0abe3c6ae47936",
      "sha1" : "6ec1c9bec76e168dc9028137a00ace68687b11ca",
      "md5" : "5d39cc91860ee84e3404e0d5c812e4fb"
    } ]
  }, {
    "name" : "sourcesElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "bip39-0.86.0.jar",
      "url" : "bip39-0.86.0.jar",
      "size" : 2701,
      "sha512" : "c3ac61d8134e07ef1db777b6b991666b4fac2f880dbeaf8800e866518140cca765affa3e8a53b986bd2412e96f13a6b313d8989017c4e834f7a7cfa157ee6436",
      "sha256" : "24071e04823f4bb921cd17212feb654c7743222407579c5eccdf8e6b2d323848",
      "sha1" : "8f9c9b5e3111908a4322c06082696fdfd6a88083",
      "md5" : "f29631a90a2537eee2e18101b32ea87c"
    } ]
  }, {
    "name" : "javadocElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "javadoc",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "bip39-0.86.0.jar",
      "url" : "bip39-0.86.0.jar",
      "size" : 261,
      "sha512" : "1bec0a81386b6be3809b567f8885d0d3f668dfe12e9581e9e346d6f2c659de2b3f78bd36acd305512cb0fa6f70a90289205cfd71a5dac1707559865727c771ab",
      "sha256" : "20bbc5a82338cd4884a79659399d4aa706b5ae9977e0b4be1db6a1ac2b940b2c",
      "sha1" : "601304c6fe0b8cb63a304ff113912284d4ec416c",
      "md5" : "545ba0a536d10375d2d3a6244e03b76d"
    } ]
  } ]
}