{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.0.2"
    }
  },
  "component" : {
    "group" : "com.github.komputing",
    "module" : "khash",
    "version" : "1.1.1",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "metadataApiElements",
    "attributes" : {
      "org.gradle.usage" : "kotlin-metadata",
      "org.jetbrains.kotlin.platform.type" : "common"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-common",
      "version" : {
        "requires" : "1.5.10"
      }
    } ],
    "files" : [ {
      "name" : "sha256-1.1.1.jar",
      "url" : "sha256-1.1.1.jar",
      "size" : 4876,
      "sha512" : "4ab4b0d466652c94d54a950c8695def37fe202dc37c736519795cca00f27b8348cfd11c595c75e588830585aee223507c94e712ed8205f0219918e96ef61b88c",
      "sha256" : "e5d119c0144f8919050204da53ef8a50d4a2f8b04dedb3b2e2a0b4bd91121352",
      "sha1" : "8a3032dac0933ffa94b387903f4368293aea107d",
      "md5" : "b4f371d32ba8362072bf4cf66fa95679"
    } ]
  }, {
    "name" : "commonMainMetadataElements",
    "attributes" : {
      "org.gradle.usage" : "kotlin-api",
      "org.jetbrains.kotlin.platform.type" : "common"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-common",
      "version" : {
        "requires" : "1.5.10"
      }
    } ],
    "files" : [ {
      "name" : "sha256-1.1.1.jar",
      "url" : "sha256-1.1.1.jar",
      "size" : 4335,
      "sha512" : "511ad13fd90234a37fc7eaf428ae1155fd2ae39775884ef4da24bd6af1f899cd56bd7aa6e7371662ebcffb3a09bb75084f17782929cb313ba921ed737fbc7632",
      "sha256" : "9bc306e8ae3db0c014e1cf3084d08bb683ef2084dc17d99ee9dd3f4f03ad7f8e",
      "sha1" : "d3ab8d09be4bb86e96beb2c6ed3330c92bcee3b4",
      "md5" : "e99ce477a01495b57e895ae7c23c77d2"
    } ]
  }, {
    "name" : "jsLegacyApiElements-published",
    "attributes" : {
      "org.gradle.usage" : "kotlin-api",
      "org.jetbrains.kotlin.js.compiler" : "legacy",
      "org.jetbrains.kotlin.platform.type" : "js"
    },
    "available-at" : {
      "url" : "../../sha256-js/1.1.1/sha256-js-1.1.1.module",
      "group" : "com.github.komputing.khash",
      "module" : "sha256-js",
      "version" : "1.1.1"
    }
  }, {
    "name" : "jsLegacyRuntimeElements-published",
    "attributes" : {
      "org.gradle.usage" : "kotlin-runtime",
      "org.jetbrains.kotlin.js.compiler" : "legacy",
      "org.jetbrains.kotlin.platform.type" : "js"
    },
    "available-at" : {
      "url" : "../../sha256-js/1.1.1/sha256-js-1.1.1.module",
      "group" : "com.github.komputing.khash",
      "module" : "sha256-js",
      "version" : "1.1.1"
    }
  }, {
    "name" : "jsIrApiElements-published",
    "attributes" : {
      "org.gradle.usage" : "kotlin-api",
      "org.jetbrains.kotlin.js.compiler" : "ir",
      "org.jetbrains.kotlin.platform.type" : "js"
    },
    "available-at" : {
      "url" : "../../sha256-js/1.1.1/sha256-js-1.1.1.module",
      "group" : "com.github.komputing.khash",
      "module" : "sha256-js",
      "version" : "1.1.1"
    }
  }, {
    "name" : "jsIrRuntimeElements-published",
    "attributes" : {
      "org.gradle.usage" : "kotlin-runtime",
      "org.jetbrains.kotlin.js.compiler" : "ir",
      "org.jetbrains.kotlin.platform.type" : "js"
    },
    "available-at" : {
      "url" : "../../sha256-js/1.1.1/sha256-js-1.1.1.module",
      "group" : "com.github.komputing.khash",
      "module" : "sha256-js",
      "version" : "1.1.1"
    }
  }, {
    "name" : "jvmApiElements-published",
    "attributes" : {
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "available-at" : {
      "url" : "../../sha256-jvm/1.1.1/sha256-jvm-1.1.1.module",
      "group" : "com.github.komputing.khash",
      "module" : "sha256-jvm",
      "version" : "1.1.1"
    }
  }, {
    "name" : "jvmRuntimeElements-published",
    "attributes" : {
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "available-at" : {
      "url" : "../../sha256-jvm/1.1.1/sha256-jvm-1.1.1.module",
      "group" : "com.github.komputing.khash",
      "module" : "sha256-jvm",
      "version" : "1.1.1"
    }
  } ]
}